#include <iostream>
#include <vector>
#include <algorithm>
#include "detector.hpp"
#include "goodW.h"

int main() {

	char lastL;
	char firstL;
    int size;
    std::string notIncl;

	std::cout << "Enter the first letter of the word: ";
	std::cin >> firstL;
	std::cout << '\n';

	std::cout << "Enter the last letter of the word: ";
	std::cin >> lastL;
	std::cout << '\n';

    std::cout << "Not including letter: ";
    std::cin >> notIncl;
    std::cout << '\n';

    std::cout << "Size of word: ";
    std::cin >> size;
    std::cout << '\n';

	std::vector<std::string> words = { "ability","able","abortion","about","above","abroad","absence","absolute","absolutely",
    "absorb","abuse","academic","accept","access","accident","accompany","accomplish","according","account",
    "accurate","accuse","achieve","achievement","acid","acknowledge","acquire","across","act","action",
    "active","activist","activity","actor","actress","actual","actually","ad","adapt","add",
    "addition","additional","address","adequate","adjust","adjustment","administration","administrator","admire","admission",
    "admit","adolescent","adopt","adult","advance","advanced","advantage","adventure","advertising","advice",
    "advise","adviser","advocate","affair","affect","afford","afraid","African","African - American","after",
    "afternoon","again","against","age","agency","agenda","agent","aggressive","ago","agree",
    "agreement","agricultural","ah","ahead","aid","aide","AIDS","aim","air","aircraft",
    "airline","airport","album","alcohol","alive","all","alliance","allow","ally","almost",
    "alone","along","already","also","alter","alternative","although","always","AM","amazing",
    "American","among","amount","analysis","analyst","analyze","ancient","and","anger","angle",
    "angry","animal","anniversary","announce","annual","another","answer","anticipate","anxiety","any",
    "anybody","anymore","anyone","anything","anyway","anywhere","apart","apartment","apparent","apparently",
    "appeal","appear","appearance","apple","application","apply","appoint","appointment","appreciate","approach",
    "appropriate","approval","approve","approximately","Arab","architect","area","argue","argument","arise",
    "arm","armed","army","around","arrange","arrangement","arrest","arrival","arrive","art",
    "article","artist","artistic","as","Asian","aside","ask","asleep","aspect","assault",
    "assert","assess","assessment","asset","assign","assignment","assist","assistance","assistant","associate",
    "association","assume","assumption","assure","at","athlete","athletic","atmosphere","attach","attack",
    "attempt","attend","attention","attitude","attorney","attract","attractive","attribute","audience","author",
    "authority","auto","available","average","avoid","award","aware","awareness","away","awful",
    "baby","back","background","bad","badly","bag","bake","balance","ball","ban",
    "band","bank","bar","barely","barrel","barrier","base","baseball","basic","basically",
    "basis","basket","basketball","bathroom","battery","battle","be","beach","bean","bear",
    "beat","beautiful","beauty","because","become","bed","bedroom","beer","before","begin",
    "beginning","behavior","behind","being","belief","believe","bell","belong","below","belt",
    "bench","bend","beneath","benefit","beside","besides","best","bet","better","between",
    "beyond","Bible","big","bike","bill","billion","bind","biological","bird","birth",
    "birthday","bit","bite","black","blade","blame","blanket","blind","block","blood",
    "blow","blue","board","boat","body","bomb","bombing","bond","bone","book",
    "boom","boot","border","born","borrow","boss","both","bother","bottle","bottom",
    "boundary","bowl","box","boy","boyfriend","brain","branch","brand","bread","break",
    "breakfast","breast","breath","breathe","brick","bridge","brief","briefly","bright","brilliant",
    "bring","British","broad","broken","brother","brown","brush","buck","budget","build",
    "building","bullet","bunch","burden","burn","bury","bus","business","busy","but",
    "butter","button","buy","buyer","by","cabin","cabinet","cable","cake","calculate",
    "call","camera","camp","campaign","campus","can","Canadian","cancer","candidate","cap",
    "capability","capable","capacity","capital","captain","capture","car","carbon","card","care",
    "career","careful","carefully","carrier","carry","case","cash","cast","cat","catch",
    "category","Catholic","cause","ceiling","celebrate","celebration","celebrity","cell","center","central",
    "century","CEO","ceremony","certain","certainly","chain","chair","chairman","challenge","chamber",
    "champion","championship","chance","change","changing","channel","chapter","character","characteristic","characterize",
    "charge","charity","chart","chase","cheap","check","cheek","cheese","chef","chemical",
    "chest","chicken","chief","child","childhood","Chinese","chip","chocolate","choice","cholesterol",
    "choose","Christian","Christmas","church","cigarette","circle","circumstance","cite","citizen","city",
    "civil","civilian","claim","class","classic","classroom","clean","clear","clearly","client",
    "climate","climb","clinic","clinical","clock","close","closely","closer","clothes","clothing",
    "cloud","club","clue","cluster","coach","coal","coalition","coast","coat","code",
    "coffee","cognitive","cold","collapse","colleague","collect","collection","collective","college","colonial",
    "color","column","combination","combine","come","comedy","comfort","comfortable","command","commander",
    "comment","commercial","commission","commit","commitment","committee","common","communicate","communication","community",
    "company","compare","comparison","compete","competition","competitive","competitor","complain","complaint","complete",
    "completely","complex","complicated","component","compose","composition","comprehensive","computer","concentrate","concentration",
    "concept","concern","concerned","concert","conclude","conclusion","concrete","condition","conduct","conference",
    "confidence","confident","confirm","conflict","confront","confusion","Congress","congressional","connect","connection",
    "consciousness","consensus","consequence","conservative","consider","considerable","consideration","consist","consistent","constant",
    "constantly","constitute","constitutional","construct","construction","consultant","consume","consumer","consumption","contact",
    "contain","container","contemporary","content","contest","context","continue","continued","contract","contrast",
    "contribute","contribution","control","controversial","controversy","convention","conventional","conversation","convert","conviction",
    "convince","cook","cookie","cooking","cool","cooperation","cop","cope","copy","core",
    "corn","corner","corporate","corporation","correct","correspondent","cost","cotton","couch","could",
    "council","counselor","count","counter","country","county","couple","courage","course","court",
    "cousin","cover","coverage","cow","crack","craft","crash","crazy","cream","create",
    "creation","creative","creature","credit","crew","crime","criminal","crisis","criteria","critic",
    "critical","criticism","criticize","crop","cross","crowd","crucial","cry","cultural","culture",
    "cup","curious","current","currently","curriculum","custom","customer","cut","cycle","dad",
    "daily","damage","dance","danger","dangerous","dare","dark","darkness","data","date",
    "daughter","day","dead","deal","dealer","dear","death","debate","debt","decade",
    "decide","decision","deck","declare","decline","decrease","deep","deeply","deer","defeat",
    "defend","defendant","defense","defensive","deficit","define","definitely","definition","degree","delay",
    "deliver","delivery","demand","democracy","Democrat","democratic","demonstrate","demonstration","deny","department",
    "depend","dependent","depending","depict","depression","depth","deputy","derive","describe","description",
    "desert","deserve","design","designer","desire","desk","desperate","despite","destroy","destruction",
    "detail","detailed","detect","determine","develop","developing","development","device","devote","dialogue",
    "die","diet","differ","difference","different","differently","difficult","difficulty","dig","digital",
    "dimension","dining","dinner","direct","direction","directly","director","dirt","dirty","disability",
    "disagree","disappear","disaster","discipline","discourse","discover","discovery","discrimination","discuss","discussion",
    "disease","dish","dismiss","disorder","display","dispute","distance","distant","distinct","distinction",
    "distinguish","distribute","distribution","district","diverse","diversity","divide","division","divorce","DNA",
    "do","doctor","document","dog","domestic","dominant","dominate","door","double","doubt",
    "down","downtown","dozen","draft","drag","drama","dramatic","dramatically","draw","drawing",
    "dream","dress","drink","drive","driver","drop","drug","dry","due","during",
    "dust","duty","each","eager","ear","early","earn","earnings","earth","ease",
    "easily","east","eastern","easy","eat","economic","economics","economist","economy","edge",
    "edition","editor","educate","education","educational","educator","effect","effective","effectively","efficiency",
    "efficient","effort","egg","eight","either","elderly","elect","election","electric","electricity",
    "electronic","element","elementary","eliminate","elite","else","elsewhere","e - mail","embrace","emerge",
    "emergency","emission","emotion","emotional","emphasis","emphasize","employ","employee","employer","employment",
    "empty","enable","encounter","encourage","end","enemy","energy","enforcement","engage","engine",
    "engineer","engineering","English","enhance","enjoy","enormous","enough","ensure","enter","enterprise",
    "entertainment","entire","entirely","entrance","entry","environment","environmental","episode","equal","equally",
    "equipment","era","error","escape","especially","essay","essential","essentially","establish","establishment",
    "estate","estimate","etc","ethics","ethnic","European","evaluate","evaluation","even","evening",
    "event","eventually","ever","every","everybody","everyday","everyone","everything","everywhere","evidence",
    "evolution","evolve","exact","exactly","examination","examine","example","exceed","excellent","except",
    "exception","exchange","exciting","executive","exercise","exhibit","exhibition","exist","existence","existing",
    "expand","expansion","expect","expectation","expense","expensive","experience","experiment","expert","explain",
    "explanation","explode","explore","explosion","expose","exposure","express","expression","extend", "extension","extra","extract","extreme","extremely","eye","face","facility","fact",
    "factor","factory","faculty","fade","fail","failure","fair","fairly","faith","fall",
    "false","familiar","family","famous","fan","fantasy","far","farm","farmer","fashion",
    "fast","fat","fate","father","fault","favor","favorite","fear","feature","federal",
    "fee","feed","feel","feeling","fellow","female","fence","festival","fetch","fever",
    "few","fiber","fiction","field","fifteen","fifth","fifty","fight","fighter","fighting",
    "figure","file","fill","film","final","finally","finance","financial","find","finding",
    "fine","finger","finish","fire","firm","first","fish","fishing","fit","fitness",
    "five","fix","flag","flame","flash","flat","flavor","flee","flesh","flight",
    "floor","flour","flow","flower","fly","focus","follow","following","food","foot",
    "football","for","force","foreign","forest","forever","forget","form","formal","formation",
    "former","formula","forth","forty","forward","found","foundation","founder","four","fourth",
    "frame","framework","free","freedom","freeze","French","frequency","frequent","frequently","fresh",
    "friend","friendly","friendship","from","front","fruit","frustration","fuel","full","fully",
    "fun","function","fund","fundamental","funding","funeral","funny","furniture","further","future",
    "gain","galaxy","game","gang","gap","garage","garden","garlic","gas","gate",
    "gather","gay","gaze","gear","gender","gene","general","generally","generate","generation",
    "genetic","gentle","gentleman","gently","genuine","geography","gesture","get","ghost","giant",
    "gift","girl","girlfriend","give","given","glad","glass","global","glove","go",
    "goal","God","gold","golden","golf","good","government","governor","grab","grade",
    "gradually","graduate","grain","grand","grandfather","grandmother","grant","grass","grave","gray",
    "great","greatest","green","grocery","ground","group","grow","growing","growth","guarantee",
    "guard","guess","guest","guide","guideline","guilty","gun","guy","habit","habitat",
    "hair","half","hall","hand","handful","handle","hang","happen","happy","hard",
    "hardly","hardware","harm","harmful","hat","hate","have","he","head","headline",
    "health","healthy","hear","hearing","heart","heat","heaven","heavily","heavy","heel",
    "height","helicopter","hell","hello","help","helpful","her","here","heritage","hero",
    "herself","hey","hi","hide","high","highlight","highly","highway","hill","him",
    "himself","hip","hire","his","historical","history","hit","hold","hole","holiday",
    "holy","home","homeland","honest","honey","honor","hope","horizon","horror","horse",
    "hospital","host","hot","hotel","hour","house","household","housing","how","however",
    "huge","human","humor","hundred","hungry","hunter","hurry","hurt","husband","hypothesis",
    "ice","idea","ideal","identification","identify","identity","ie","if","ignore","ill",
    "illegal","illustrate","image","imagination","imagine","immediate","immediately","impact","implement","implication",
    "imply","importance","important","impose","impossible","impress","impression","improve","improvement","in",
    "incentive","incident","include","including","income","incorporate","increase","increased","increasing","increasingly",
    "indeed","independence","independent","index","Indian","indicate","indication","individual","industrial","industry",
    "infant","infection","inflation","influence","inform","information","ingredient","initial","initially","initiative",
    "injury","inner","innocent","input","inquiry","inside","insight","insist","inspire","install",
    "instance","instant","instead","institution","institutional","instruction","instructor","insurance","intellectual","intelligence",
    "intend","intense","intensity","intent","interaction","interest","interested","interesting","internal","international",
    "Internet","interpret","interpretation","interrupt","interval","intervention","interview","into","introduce","introduction",
    "invasion","invest","investigate","investigation","investment","investor","invite","involve","involved","involvement",
    "iron","is","Islamic","island","issue","it","Italian","item","its","itself",
    "jacket","jail","Japanese","job","join","joint","joke","journal","journalist","journey",
    "joy","judge","judgment","juice","jump","junior","jury","just","justice","justify",
    "keep","key","kick","kid","kill","killer","killing","kind","king","kiss",
    "kitchen","knee","knife","knock","know","knowledge","lab","label","labor","laboratory",
    "lack","ladder","lady","lake","land","landscape","language","large","largely","last",
    "late","later","Latin","latter","laugh","launch","law","lawn","lawsuit","lawyer",
    "lay","layer","lazy","lead","leader","leadership","leading","leaf","league","lean",
    "learn","learning","least","leather","leave","lecture","left","leg","legacy","legal",
    "legend","legislation","legitimate","leisure","lend","length","less","lesson","let","letter",
    "level","liberal","library","license","lie","life","lifestyle","lifetime","lift","light",
    "like","likely","limit","limitation","limited","line","link","lip","list","listen",
    "literally","literary","literature","little","live","living","load","loan","local","locate",
    "location","lock","long","long-term","look","loose","lose","loss","lost","lot",
    "lots","loud","love","lovely","lover","low","lower","loyal","luck","lucky",
    "lunch","lung","machine","mad","magazine","mail","main","mainly","maintain","maintenance",
    "major","majority","make","maker","male","mall","man","manage","management","manager",
    "manner","manufacturer","many","map","march","mark","market","marketing","marriage","married",
    "marry","mask","mass","massive","master","match","material","math","matter","may",
    "maybe","mayor","me","meal","mean","meaning","meanwhile","measure","measurement","meat",
    "mechanism","media","medical","medicine","medium","meet","meeting","member","membership","memory",
    "mental","mention","menu","mere","merely","mess","message","metal","meter","method",
    "methodology","mid","middle","might","military","milk","million","mind","mine","minor",
    "minority","minute","miracle","mirror","miss","mission","mistake","mix","mixture","mode",
    "model","moderate","modern","modest","moment","money","monitor","month","mood","moon",
    "moral","more","moreover","morning","mortgage","most","mostly","mother","motion","motivate",
    "motivation","motor","mount","mountain","mouse","mouth","move","movement","movie","Mr",
    "Mrs","Ms","much","multiple","murder","muscle","museum","music","musical","musician",
    "must","mutual","my","myself","mystery","myth","narrow","nation","national","native",
    "natural","naturally","nature","near","nearby","nearly","necessarily","necessary","neck","need",
    "negative","neglect","neither","nerve","nervous","net","network","never","nevertheless","new",
    "news","newspaper","next","nice","night","nine","no","nobody","nod","noise",
    "nomination","none","nonetheless","normal","normally","north","northern","nose","not","note",
    "nothing","notice","notion","novel","now","nowhere","nuclear","number","numerous","nurse",
    "object","objective","obligation","observation","observe","observer","obtain","obvious","obviously","occasion",
    "occasionally","occupy","occur","ocean","odd","odds","of","off","offense","offer",
    "office","officer","official","often","oh","oil","ok","okay","old","Olympic",
    "on","once","one","ongoing","only","onto","open","opening","operate","operation",
    "operator","opinion","opponent","opportunity","oppose","opposite","opposition","option","or","orange",
    "order","ordinary","organization","organize","orientation","origin","original","originally","other","others",
    "otherwise","ought","our","ours","ourselves","out","outcome","outside","oven","over",
    "overall","overcome","owe","own","owner","pace","pack","package","page","pain",
    "painful","paint","painter","painting","pair","pale","pan","panel","pant","paper",
    "parent","park","parking","part","participant","participate","participation","particular","particularly","partly",
    "partner","partnership","party","pass","passage","passenger","passion","past","patch","path",
    "patient","pattern","pause","pay","payment","peace","peak","peer","pen","penalty",
    "people","pepper","per","perceive","percentage","perception","perfect","perfectly","perform","performance",
    "perhaps","period","permanent","permission","permit","person","personal","personality","personally","personnel",
    "perspective","persuade","pet","phase","phenomenon","philosophy","phone","photo","photograph","photographer",
    "phrase","physical","physically","physician","piano","pick","picture","piece","pile","pilot",
    "pine","pink","pipe","pitch","place","plan","plane","planet","planning","plant",
    "plastic","plate","platform","play","player","please","pleasure","plenty","plot","plus",
    "PM","pocket","poem","poet","poetry","point","pole","police","policy","political",
    "politically","politician","politics","poll","pollution","pool","poor","pop","popular","population",
    "porch","port","portion","portrait","portray","pose","position","positive","possess","possibility",
    "possible","possibly","post","pot","potato","potential","potentially","pound","pour","poverty",
    "powder","power","powerful","practical","practice","pray","prayer","precisely","predict","prefer",
    "preference","pregnant","preparation","prepare","prescribe","presence","present","presentation","preserve","president",
    "presidential","press","pressure","pretty","prevent","previous","previously","price","pride","primary",
    "prime","principal","principle","print","prior","priority","prison","privacy","private","probably",
    "problem","procedure","proceed","process","produce","producer","product","production","profession","professional",
    "professor","profile","profit","program","progress","project","prominent","promise","promote","prompt",
    "proof","proper","properly","property","proportion","proposal","propose","prosecution","prospect","protect",
    "protection","protein","protest","proud","prove","provide","provider","province","provision","psychological",
    "psychologist","psychology","public","publication","publicity","publish","pull","pulse","pump","punishment",
    "purchase","pure","purpose","pursue","push","put","qualification","qualify","quality","quarter",
    "quarterback","question","quick","quickly","quiet","quietly","quit","quite","quote","race",
    "racial","radical","radio","rail","rain","raise","range","rank","rapid","rapidly",
    "rare","rarely","rate","rather","rating","ratio","raw","reach","react","reaction",
    "read","reader","reading","ready","real","reality","realize","really","reason","reasonable",
    "recall","receive","recent","recently","recipe","recognition","recognize","recommend","recommendation","record",
    "recording","recover","recovery","recruit","red","reduce","reduction","refer","reference","reflect",
    "reflection","reform","refuse","regard","regarding","region","regional","register","regular","regularly",
    "regulate","regulation","reinforce","reject","relate","related","relationship","relative","relatively","relax",
    "release","relevant","rely","remain","remaining","remark","remarkable","remember","remind","remote",
    "remove","repeat","repeatedly","replace","reply","report","reporter","represent","representation","representative",
    "reproduce","republic","reputation","request","require","requirement","research","researcher","resemble","reservation",
    "resident","resist","resistance","resolution","resolve","resort","resource","respect","respond","response",
    "responsibility","responsible","rest","restaurant","restore","restrict","restriction","result","retain","retire",
    "retirement","return","reveal","revenue","review","revolution","rhythm","rice","rich","rid",
    "ride","rifle","right","ring","rise","risk","rival","river","road","rock",
    "role","roll","romantic","roof","room","root","rope","rough","round","route",
    "routine","row","royal","rub","rule","run","runner","running","rural","rush",
    "Russian","sacred","sad","safe","safety","sake","salad","salary","sale","salt",
    "same","sample","sanction","sand","satellite","satisfaction","satisfy","sauce","save","saving",
    "say","scale","scan","scandal","scared","scenario","scene","schedule","scheme","school",
    "science","scientific","scientist","score","scratch","screen","script","sea","search","season",
    "seat","second","secondary","secret","secretary","section","sector","secure","security","see",
    "seed","seek","seem","segment","seize","select","selection","self","sell","semester",
    "seminar","senate","senator","send","senior","sense","sensitive","sentence","separate","sequence",
    "series","serious","seriously","serve","service","session","set","setting","settle","settlement",
    "seven","several","severe","sex","sexual","shade","shadow","shake","shall","shallow",
    "shape","share","sharp","she","sheet","shelf","shell","shelter","shift","shine",
    "ship","shirt","shit","shock","shoe","shoot","shooting","shop","shopping","short",
    "shortly","shot","should","shoulder","shout","show","shower","shrug","shut","sick",
    "side","sigh","sight","sign","signal","significance","significant","significantly","silence","silent",
    "silver","similar","similarly","simple","simply","sin","since","sing","singer","single",
    "sink","sir","sister","sit","site","situation","six","size","skill","skin",
    "sky","slave","sleep","slice","slide","slight","slightly","slip","slow","slowly",
    "small","smart","smell","smile","smoke","smooth","snap","snow","so","soccer",
    "social","society","soft","software","soil","solar","soldier","solid","solution","solve",
    "some","somebody","somehow","someone","something","sometimes","somewhat","somewhere","son","song",
    "soon","sophisticated","sorry","sort","soul","sound","soup","source","south","southern",
    "space","span","speak","speaker","special","specialist","species","specific","specifically","speech",
    "speed","spend","spending","sphere","spiritual","split","sport","spot","spray","spread",
    "spring","square","squeeze","stability","stable","staff","stage","stair","stake","stand",
    "standard","standing","star","stare","start","state","statement","station","statistics","status",
    "stay","steady","steal","steam","steel","step","stick","still","stir","stock",
    "stomach","stone","stop","storage","store","storm","story","straight","strain","strange",
    "stranger","strategic","strategy","stream","street","strength","strengthen","stress","stretch","strike",
    "string","strip","stroke","strong","strongly","structure","struggle","student","studio","study",
    "stuff","stupid","style","subject","submit","subsequent","substance","substantial","succeed","success",
    "successful","successfully","such","sudden","suddenly","suffer","sufficient","sugar","suggest","suggestion",
    "suicide","suit","summer","summit","sun","super","supply","support","supporter","suppose",
    "supposed","sure","surface","surgery","surprise","surprised","surprising","surprisingly","surround","survey",
    "survival","survive","suspect","sustain","swear","sweep","sweet","swim","swing","switch",
    "symbol","sympathy","system","table","tackle","tactic","tail","take","tale","talent",
    "talk","tall","tank","tap","target","task","taste","tax","teach","teacher",
    "teaching","team","tear","technical","technique","technology","teen","telephone","television","tell",
    "temperature","temporary","ten","tend","tendency","tennis","tension","term","terminal","terms",
    "terrible","territory","terror","terrorism","test","text","than","thank","thanks","that",
    "the","theater","their","them","theme","themselves","then","theory","therapy","there",
    "therefore","these","they","thick","thin","thing","think","thinking","third","thirty",
    "this","those","though","thought","thousand","threat","threaten","three","throat","through",
    "throughout","throw","thus","tie","tight","time","tiny","tip","tire","tissue",
    "title","to","tobacco","today","toe","together","tomorrow","tone","tongue","tonight",
    "too","tool","tooth","top","topic","total","totally","touch","tough","tour",
    "tourist","toward","towards","tower","town","toy","trace","track","trade","tradition",
    "traditional","traffic","tragedy","trail","train","training","transfer","transform","transition","translate",
    "transport","transportation","trap","travel","treat","treatment","treaty","tree","trend","trial",
    "tribe","trick","trip","troop","trouble","truck","true","truly","trust","truth",
    "try","tube","tunnel","turn","TV","twelve","twenty","twice","two","type",
    "typical","typically","ugly","ultimate","ultimately","unable","uncle","under","undergo","understand",
    "understanding","undertake","unemployed","uniform","union","unique","unit","United","universal","universe",
    "university","unknown","unless","unlike","unlikely","until","unusual","up","upon","upper",
    "urban","urge","urgent","us","use","used","useful","user","usual","usually",
    "utility","vacation","valley","valuable","value","variable","variation","variety","various","vary",
    "vast","vegetable","vehicle","venture","version","very","vessel","victim","victory","video",
    "view","viewer","village","violate","violation","violence","violent","virtually","virtue","virus",
    "visible","vision","visit","visitor","visual","vital","voice","volume","vote","voter",
    "vs","vulnerable","wage","wait","wake","walk","wall","wander","want","war",
    "warm","warn","warning","wash","waste","watch","water","wave","way","we",
    "weak","wealth","weapon","wear","weather","wedding","week","weekend","weekly","weigh",
    "weight","welcome","well","west","western","wet","what","whatever","wheel","when",
    "whenever","where","whereas","whether","which","while","whisper","white","who","whole",
    "whom","whose","why","wide","widely","widespread","wife","wild","will","willing",
    "win","wind","window","wine","wing","winner","winter","wipe","wire","wisdom",
    "wise","wish","with","withdraw","within","without","witness","woman","wonder","wonderful",
    "wood","wooden","word","work","worker","working","workshop","world","worried","worry",
    "worth","would","wound","wrap","write","writer","writing","wrong","yard","yeah",
    "year","yell","yellow","yes","yesterday","yet","you","young","your","yours",
    "yourself","youth","zero","zone","zoo"};

    detector(words, firstL, lastL,size, notIncl);

	//auto it = std::find(words.begin(), words.end(), detector(words));

	return 0;
}
